name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Kích hoạt workflow khi có push lên nhánh 'main'
  pull_request:
    branches:
      - main # Chạy workflow khi có pull request đến nhánh 'main'

env:
  DOCKER_IMAGE_NAME: your-dockerhub-quochuy8d/my-php-app # Thay thế bằng tên người dùng Docker Hub của bạn và tên repo

jobs:
  build:
    runs-on: ubuntu-latest # Chạy job trên runner Ubuntu mới nhất

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Bước này kéo mã nguồn từ repo của bạn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Thiết lập Docker Buildx để build image hiệu quả

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Lấy tên người dùng từ GitHub Secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Lấy mật khẩu từ GitHub Secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Đường dẫn đến Dockerfile (thư mục hiện tại)
          file: ./Dockerfile # Đường dẫn đến Dockerfile của bạn
          push: true # Tải image lên registry sau khi build
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest # Tag 'latest'
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Tag với SHA của commit (duy nhất)
          cache-from: type=gha # Tận dụng cache của GitHub Actions để tăng tốc build
          cache-to: type=gha,mode=max # Lưu cache để sử dụng trong các lần build sau